"""Reinitialization with all 9 fields

Revision ID: 75d59e3317ab
Revises: 
Create Date: 2025-10-04 13:15:18.106639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d59e3317ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accountNo', sa.String(length=120), nullable=False),
    sa.Column('profitCenter', sa.String(length=120), nullable=True),
    sa.Column('costCenter', sa.String(length=120), nullable=True),
    sa.Column('branchName', sa.String(length=120), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('houseBank', sa.String(length=120), nullable=True),
    sa.Column('bankGL', sa.String(length=120), nullable=True),
    sa.Column('bankName', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapping_accountNo'), ['accountNo'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role'))

    op.drop_table('user')
    with op.batch_alter_table('mapping', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapping_accountNo'))

    op.drop_table('mapping')
    # ### end Alembic commands ###
