"""Added email automation fields

Revision ID: e9d368d75255
Revises: 75d59e3317ab
Create Date: 2026-03-13 11:33:10.128466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9d368d75255'
down_revision = '75d59e3317ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emailSender', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('emailSubject', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('zipPassword', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mapping', schema=None) as batch_op:
        batch_op.drop_column('zipPassword')
        batch_op.drop_column('emailSubject')
        batch_op.drop_column('emailSender')

    # ### end Alembic commands ###
